# Generated by Django 5.1.4 on 2024-12-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(db_index=True, max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18, default=0, max_digits=36
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("txid", models.CharField(max_length=255, unique=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=18, max_digits=36),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet_app.wallet",
                    ),
                ),
            ],
        ),
    ]
